/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view_nguoihoc;

import Model.Model;
import Reporsitories.reporsitories;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rinbo
 */
public class view_nguoihoc extends javax.swing.JFrame {

    /**
     * Creates new form view_nguoihoc
     */
    private Reporsitories.reporsitories rp = new reporsitories();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = 0;
    public view_nguoihoc() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fillTable(rp.getAll());
        i = 0;
        this.showdata(i);
    }
    public void fillTable(ArrayList<Model> list){
        mol = (DefaultTableModel) tbl_nguoihoc.getModel();
        mol.setRowCount(0);
        for (Model x : list) {
            mol.addRow(x.toDaTaRow());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_HoTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_nguoihoc = new javax.swing.JTable();
        tbn_them = new javax.swing.JButton();
        tbn_sua = new javax.swing.JButton();
        tbn_xoa = new javax.swing.JButton();
        tbn_reset = new javax.swing.JButton();
        tbn_sapXep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Người Học");

        jLabel2.setText("Email:");

        jLabel3.setText("Họ Tên");

        jLabel4.setText("Mã Khách Hàng");

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane1.setViewportView(txt_GhiChu);

        jLabel5.setText("Ghi chú");

        tbl_nguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ Tên", "Email", "Ghi Chú"
            }
        ));
        tbl_nguoihoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nguoihocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_nguoihoc);

        tbn_them.setText("Thêm");
        tbn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_themActionPerformed(evt);
            }
        });

        tbn_sua.setText("Sửa");
        tbn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_suaActionPerformed(evt);
            }
        });

        tbn_xoa.setText("Xóa");
        tbn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_xoaActionPerformed(evt);
            }
        });

        tbn_reset.setText("Reset");
        tbn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_resetActionPerformed(evt);
            }
        });

        tbn_sapXep.setText("Sắp xếp");
        tbn_sapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_sapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tbn_them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbn_sua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbn_xoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbn_sapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(tbn_them))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbn_xoa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbn_sua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbn_reset)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(tbn_sapXep)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void tbn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_themActionPerformed
        // TODO add your handling code here:
        if(this.readForm()!=null){
            if (rp.them(this.readForm())>0) {
                JOptionPane.showMessageDialog(this, "thêm thành công");
                this.fillTable(rp.getAll());
            }else{
                 JOptionPane.showMessageDialog(this, "thêm thất bại");
            }
 
        }
    }//GEN-LAST:event_tbn_themActionPerformed

    private void tbl_nguoihocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nguoihocMouseClicked
        // TODO add your handling code here:
        i = tbl_nguoihoc.getSelectedRow();
        txt_maKH.setEnabled(false);
        this.showdata(i);
        
    }//GEN-LAST:event_tbl_nguoihocMouseClicked

    private void tbn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_resetActionPerformed
        // TODO add your handling code here:
        txt_maKH.setText("");
        txt_HoTen.setText("");
        txt_Email.setText("");
        txt_GhiChu.setText("");
        
    }//GEN-LAST:event_tbn_resetActionPerformed

    private void tbn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_suaActionPerformed
        // TODO add your handling code here:
        i = tbl_nguoihoc.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn dòng ");
        }else{
            int maKH = Integer.parseInt(tbl_nguoihoc.getValueAt(i, 0).toString());
            if (readForm()!= null) {
                if (rp.sua(maKH, this.readForm())>0) {
                    JOptionPane.showMessageDialog(this, "sửa thành công");
                    this.fillTable(rp.getAll());
                }else{
                    JOptionPane.showMessageDialog(this, "sửa thất bại");
                }
            }
        }
    }//GEN-LAST:event_tbn_suaActionPerformed

    private void tbn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_xoaActionPerformed
        // TODO add your handling code here:
        i = tbl_nguoihoc.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "bạn chưa chọn dòng "); 
        }else{
            int maKH = Integer.parseInt(tbl_nguoihoc.getValueAt(i, 0).toString());
            if (this.readForm()!= null) {
                if (rp.xoa(maKH)>0) {
                    JOptionPane.showMessageDialog(this, "xóa thành công");
                    this.fillTable(rp.getAll());
                }else{
                    JOptionPane.showMessageDialog(this, "xóa thất bại");
                }
            }
        }
    }//GEN-LAST:event_tbn_xoaActionPerformed

    private void tbn_sapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_sapXepActionPerformed
        // TODO add your handling code here:
        this.fillTable(rp.sapXep());
        
    }//GEN-LAST:event_tbn_sapXepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_nguoihoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_nguoihoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_nguoihoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_nguoihoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_nguoihoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_nguoihoc;
    private javax.swing.JButton tbn_reset;
    private javax.swing.JButton tbn_sapXep;
    private javax.swing.JButton tbn_sua;
    private javax.swing.JButton tbn_them;
    private javax.swing.JButton tbn_xoa;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_maKH;
    // End of variables declaration//GEN-END:variables
    void showdata(int i){
    txt_maKH.setText(tbl_nguoihoc.getValueAt(i, 0).toString());
    txt_HoTen.setText(tbl_nguoihoc.getValueAt(i, 1).toString());
    txt_Email.setText(tbl_nguoihoc.getValueAt(i, 2).toString());
    txt_GhiChu.setText(tbl_nguoihoc.getValueAt(i, 3).toString());
}
    Model readForm(){
       int maKH = Integer.parseInt(txt_maKH.getText().trim().toString()) ;
    
     String hoTen = txt_HoTen.getText().trim();
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền họ tên");
            txt_HoTen.requestFocus();
        }
     String email = txt_Email.getText().trim();
     if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền Email");
            txt_HoTen.requestFocus();
        }
     String ghiChu = txt_GhiChu.getText().trim();
     if (ghiChu.isEmpty()) {
            JOptionPane.showMessageDialog(this, "chưa điền ghi chú");
            txt_HoTen.requestFocus();
        }
     
     return new Model(maKH, hoTen, email, ghiChu);
    }
}
